---
    - name: Install Apache and Set Index Page
      hosts: webservers
      become: true # run it as a sudo
    
      tasks:
        - name: Install Apache
          apt:
            name: apache2
            state: present
    
        - name: Create the index.html file
          copy:
            content: |
              <h1>Welcome to Ansible!!</h1>                   
            dest: /var/www/html/index.html   
       
        - name: Ensure Apache service is running and enabled
          service:
            name: apache2
            state: started
            enabled: yes
   